export enum SettingKey {
    SYSTEM_LOCALE = 'systemLocale',
    SYSTEM_TIMEZONE = 'systemTimezone',
    DATE_FORMAT = 'dateFormat',
    TIME_FORMAT = 'timeFormat',
    DATETIME_FORMAT = 'dateTimeFormat',
    MAX_LOGIN_ATTEMPTS = 'maxLoginAttempts',
    PASSWORD_LIFETIME_IN_DAYS = 'passwordLifeTimeInDays',
    PASSWORD_REUSE_CUTOFF_IN_DAYS = 'passwordReUseCutoffInDays',
    EVALUATION_AUTOMATION_RUN_RETENTION_DAYS = 'evaluationAutomationRunRetentionDays',
    TREATMENT_FINALIZATION_UNDO_WINDOW_DAYS = 'treatmentFinalizationUndoWindowDays',
    PATIENT_CASE_MANAGER_ASSIGNABLE_HIERARCHY_RANK = 'patientCaseManagerAssignableHierarchyRank',
    SEND_WELCOME_EMAILS = 'sendWelcomeEmails',
    WELCOME_EMAIL_TEMPLATE_ID = 'welcomeEmailTemplateId',
    GOOGLE_CALENDAR_ENABLED = 'googleCalendarEnabled',
    GOOGLE_CALENDAR_CLIENT_ID = 'googleCalendarClientId',
    GOOGLE_CALENDAR_CLIENT_SECRET = 'googleCalendarClientSecret',
    GOOGLE_CALENDAR_REDIRECT_URI = 'googleCalendarRedirectUri',
}
