import { registerEnumType } from '@nestjs/graphql';

export enum CaseEventReasonContext {
    SESSION_CANCELLATION = 'SESSION_CANCELLATION',
    SUPERVISION_SESSION_CANCELLATION = 'SUPERVISION_SESSION_CANCELLATION',
    TREATMENT_FINALIZATION = 'TREATMENT_FINALIZATION',
    SUPERVISION_FINALIZATION = 'SUPERVISION_FINALIZATION',
    NEW_TREATMENT = 'NEW_TREATMENT',
    NEW_SUPERVISION = 'NEW_SUPERVISION',
    INFORMED_CONSENT_REACTIVATION = 'INFORMED_CONSENT_REACTIVATION',
    SUPERVISION_INFORMED_CONSENT_REACTIVATION = 'SUPERVISION_INFORMED_CONSENT_REACTIVATION',
}

registerEnumType(CaseEventReasonContext, {
    name: 'CaseEventReasonContext',
});
